export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const COMPLETE_FETCH_PROFILE = 'COMPLETE_FETCH_PROFILE';

export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

// Register
export const COMPLETE_REGISTER = 'COMPLETE_REGISTER'
export const COMPLETE_UPDATE_PROFILE = 'COMPLETE_UPDATE_PROFILE';

// Loader
export const LOADER_START = 'LOADING_SPINNER_START'
export const LOADER_COMPLETE = 'LOADING_SPINNER_COMPLETE'
export const LOADER_ERROR = 'LOADING_SPINNER_ERROR'
export const FORM_LOADING_START = 'FORM_LOADING_START'
export const FORM_LOADING_FINISH = 'FORM_LOADING_FINISH'

// Modal
export const MODAL_SHOW = "Modal/SHOW"
export const MODAL_HIDE = "Modal/HIDE"
export const MODAL_BUTTON_LOADING_START = "Modal/BUTTON_LOADING"
export const MODAL_BUTTON_LOADING_END = "Modal/BUTTON_FINISH"


// Exceptions
export const GET_ERRORS = 'GET_ERRORS';